### ISSUE TITLE
Associated video link is broken

### ISSUE THREAD

**Issue by dangleweed** [khinpyaephyosan/csr1000v_upgrade#2]
Thanks for posting this guide. There is no video available in youtube link you posted in the notes. 

Can you update the link please? Thanks!

**Comment by lillianphyo** [comment]
Thank you for the request. video tutorial link was updated. please kindly check this. https://www.youtube.com/watch?v=ADiRvV1BOHA

**Comment by dangleweed** [comment]
Fixed. Thanks 👍
